name: CI Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build & Test
        run: mvn -B -q clean verify

      - name: Subir resultados Allure (crudos)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: "**/allure-results"

      - name: Subir reportes JaCoCo
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jacoco-report
          path: "target/site/jacoco"

